# Generated by Django 4.2.7 on 2024-07-18 15:39

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
