# Generated by Django 4.2.7 on 2024-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_trigram_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='book', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
