# Generated by Django 4.2.7 on 2024-07-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='copy',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
