# Generated by Django 4.2.7 on 2024-07-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_available_book_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='edition',
        ),
    ]
