# Generated by Django 4.2.7 on 2024-07-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='Relentless you survive', max_length=255),
            preserve_default=False,
        ),
    ]
