# Generated by Django 4.2.7 on 2024-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books_written', to='authors.author'),
        ),
    ]
