# Generated by Django 4.2.7 on 2024-07-18 15:11
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_book_edition_book_year_remove_book_author_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
