# Generated by Django 4.2.7 on 2024-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_trigram_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
