# Generated by Django 4.2.7 on 2024-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk'], 'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
