# Generated by Django 4.2.7 on 2024-07-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_options_review_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
    ]
