# Generated by Django 4.2.7 on 2024-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default="Faxrlanasizmi, o'g'lizdan ota?"),
            preserve_default=False,
        ),
    ]
