# Generated by Django 4.2.7 on 2024-07-19 10:42

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=books.models.book_image_upload_to),
        ),
    ]
