# Generated by Django 4.2.7 on 2024-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(default='Tashkent', max_length=50),
            preserve_default=False,
        ),
    ]
