version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-%^5d_36fu=14j2=po3@&cb5bh)+prd!&^v4ja$$m9-gjaa6tw$$z"
      - "DJANGO_DEBUG=True"
      - "GITHUB_CLIENT_ID=Ov23liMj0gAtixqwuVEF"
      - "GITHUB_SECRET_KEY=259e3fe8780e977f03e447976aae78f0118cb4a6"
  db:
    image: postgres:15.4
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: